# Generated by Django 2.2.4 on 2019-08-12 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('passport_image', models.ImageField(null=True, upload_to='')),
                ('passport_serial', models.CharField(max_length=255, null=True)),
                ('birth_year', models.IntegerField(null=True)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], null=True)),
                ('nationality', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'doctor',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
            ],
            options={
                'db_table': 'speciality',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('year', models.TextField(null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor')),
            ],
            options={
                'db_table': 'doctor_type',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('hours', models.IntegerField(null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Speciality')),
            ],
            options={
                'db_table': 'doctor_training',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField(null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Speciality')),
            ],
            options={
                'db_table': 'doctor_specialization',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='MedicalCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('year', models.IntegerField(null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor')),
            ],
            options={
                'db_table': 'doctor_medical_candidate',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Faculty')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.University')),
            ],
            options={
                'db_table': 'doctor_knowledge',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField(null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor')),
            ],
            options={
                'db_table': 'doctor_function',
                'ordering': ('-id',),
            },
        ),
    ]
