# Generated by Django 2.2.4 on 2019-08-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='self_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
