# Generated by Django 2.2.4 on 2019-08-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_doctor_self_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('-name_ru',), 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('-name_ru',), 'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.AddField(
            model_name='city',
            name='name_uz',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='name_uz',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
