# Generated by Django 2.2.4 on 2019-08-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190819_0444'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='cities',
        ),
        migrations.AlterModelTable(
            name='district',
            table='districts',
        ),
    ]
