# Generated by Django 2.2.4 on 2019-08-20 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_doctor_work_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='work_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Institution'),
        ),
    ]
