# Generated by Django 2.2.4 on 2019-08-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190819_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='name',
        ),
        migrations.RemoveField(
            model_name='type',
            name='year',
        ),
        migrations.AddField(
            model_name='classtype',
            name='year',
            field=models.TextField(null=True),
        ),
    ]
