# Generated by Django 2.2.4 on 2019-08-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_messagetemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='name',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
