# Generated by Django 2.2.4 on 2019-08-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190821_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagetemplate',
            old_name='message',
            new_name='text',
        ),
    ]
