# Generated by Django 2.2.4 on 2019-08-22 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190821_0230'),
    ]

    operations = [

        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),

    ]
