# Generated by Django 2.2.4 on 2019-08-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190821_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classtype',
            name='year',
        ),
    ]
