# Generated by Django 2.2.4 on 2019-08-23 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0018_remove_classtype_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Doctor')),
                ('from_institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_inst', to='app.Institution')),
                ('to_institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_inst', to='app.Institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
