# Generated by Django 2.2.4 on 2019-08-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='register_num',
            field=models.TextField(blank=True, null=True),
        ),
    ]
