# Generated by Django 2.2.4 on 2019-08-24 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_doctor_register_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institutions_doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Doctor')),
                ('work_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Institution')),
            ],
        ),
    ]
