# Generated by Django 2.2.4 on 2019-08-24 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_institutions_doctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institutions_doctor',
            new_name='WorkPlacesList',
        ),
        migrations.AddField(
            model_name='doctor',
            name='work_places',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='app.WorkPlacesList'),
        ),
    ]
