# Generated by Django 2.2.4 on 2019-08-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190824_1212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkPlacesList',
            new_name='WorkPlaces',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='work_places',
        ),
    ]
