# Generated by Django 2.2.4 on 2019-08-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190824_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='qr_file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
