# Generated by Django 2.2.4 on 2019-08-27 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_doctor_qr_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplaces',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobs', to='app.Doctor'),
        ),
    ]
